server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lvm3632/spring-cloud-native
          default-label: main
          timeout: 5
          search-paths:
            - Chapter04/04-end/config-repo
          clone-on-start: true
          force-pull: true
